### ISSUE TITLE
would you be open to a PR for allowing experimental network imports?

### ISSUE THREAD

**Issue by mreinstein** [kmamal/packager#1]
I'm thinking something like this:

```bash
npx packager --experimental-network-imports --out-dir dist
```

This would modify the produced `cmd-runner.cmd` to:
```bash
"%0\..\bundle\node" --experimental-network-imports "%0\..\bundle\project"
```

and the produced `bash-runner.sh` to:
```bash
#!/usr/bin/env bash

set -eEu -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

cd "$DIR"
./bundle/node --experimental-network-imports bundle/project
```

**Comment by kmamal** [comment]
I think there's a lot more generality that can be added here, rather than having en explicit `--experimental-network-imports` flag only for this purpose. Maybe having a `--flags` option to specify all flags to nodejs, or maybe a `--command` options to set the entire nodejs command to run, maybe even have it work with other runtimes like deno or bun.

I haven't worked on this project in a while. Give me some time to catch up and I'll get back to you. I'll most likely do the work myself.

**Comment by mreinstein** [comment]
that's true there could be a flags option.

Another thing that might be simpler is provide an option to _not_ automatically zip the output. Not needing to first unzip the build would simplify the build/customization process.  That would keep this repo cleaner, instead of having to support whatever crazy flags one would want to add, or any other modifications of the runners for that matter.

**Comment by kmamal** [comment]
Check `v0.2.1`. I have added the `--flag` option to pass flags and the `--unzip` options to not zip up the bundle. There are some other misc changes. Mainly `-I/--include` is no longer a JSON object; you set it multiple times instead. Also I realized that `-{arch}` is absolutely necessary.

**Comment by mreinstein** [comment]
I'm not able to make this change work. I've tried 2 things:

```bash
npx packager --out-dir dist -f --experimental-network-imports

usage: packager [-h] [-v] [-a ARCH] [-i IN_DIR] [-I INCLUDE] [-f FLAG] [-o OUT_DIR] [-n OUT_NAME] [-t TARGET] [-p PLATFORM] [-u]
packager: error: argument -f/--flag: expected one argument
```

I assume that the cli argument parser sees `--experimental-network-imports` and doesn't associate it as a value belonging to `-f`

So instead I've also tried:

```bash
npx packager --out-dir dist -f experimental-network-imports
```

Which indeed generates an output bundle , but doesn't setup the flag correctly. my file:

```bash
#!/usr/bin/env bash

set -eEu -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

cd "$DIR"
./bundle/node experimental-network-imports bundle/project
```

**Comment by kmamal** [comment]
My bad, I forgot to fix the example in the README: When you need to pass a value that looks like a command-line flag, you can use the following syntax: `-f="--experimental-network-imports"`.

**Comment by mreinstein** [comment]
success!
